### ISSUE TITLE
Docs do not say how to get Jupyter token or default password

### ISSUE THREAD

**Issue by andrewb-ms** [sagemath/docker-images#28] opened 2018-01-17 02:43 UTC
Ran this command:

docker run -p 8888:8888 sagemath/sagemath-jupyter

Expected: Can go to the Jupyter notebook

Observed: 

Got this error, no way to get the token.  Docs should specify how to get token or default password.

```
Invalid password
Token authentication is enabled. You need to open the notebook server with its first-time login token in the URL, or enable a password in order to gain access. The command:

jupyter notebook list
will show you the URLs of running servers with their tokens, which you can copy and paste into your browser. For example:

Currently running servers:
http://localhost:8888/?token=c8de56fa... :: /Users/you/notebooks
Or you can paste just the token value into the password field on this page.

Cookies are required for authenticated access to notebooks.
```

**Comment by embray** [comment] 2018-01-17 14:47
Where did you get this error?  When I start the container from the latest version I observe the following output:

```
[I 14:44:40.057 NotebookApp] Using MathJax: nbextensions/mathjax/MathJax.js
[I 14:44:40.064 NotebookApp] Writing notebook server cookie secret to /home/sage/.local/share/jupyter/runtime/notebook_cookie_secret
[I 14:44:40.928 NotebookApp] Serving notebooks from local directory: /home/sage
[I 14:44:40.929 NotebookApp] 0 active kernels
[I 14:44:40.929 NotebookApp] The Jupyter Notebook is running at: http://172.17.0.2:8888/?token=2df47e8fbcbe3371b53aaf3c4959f7119c20e1c1cf598780
[I 14:44:40.929 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 14:44:40.929 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://172.17.0.2:8888/?token=2df47e8fb...
```

**Comment by pvxe** [comment] 2018-03-29 10:59
Bookmarked that URL shown some time ago when I ran my sage instance, but it seems that token is only usable once, can't confirm though as I have read just a bit about a token being put just once to set a cookie which differs from the real token, I'm sure I lost the cookie and now I can't recover the other token. 

Getting a terminal into the container with `docker exec -i -t <name> /bin/bash` didn't help to try executing
```
jupyter notebook list
```
as shown in the login page as `jupyter` because it isn't recognized as a command.

Edit: Hey! I've managed to get into the jupyter interface by running `sage -n jupyter --no-browser --ip=<ip> --port=8889` inside the container's terminal, I expected a new jupyter instance but when entered the new token in port 8889 login page I could access the same .ipynb files I could when my instance on 8888 worked, quite bizarre process to recover them though I'm pretty sure I'm messing quite bad by doing all of this but I'm just trying to help. 

In any case I could open a terminal from the web interface and execute `jupyter notebook list` and could confirm the tokens were different:

![image](https://user-images.githubusercontent.com/12409805/38087736-825b0b14-3359-11e8-9f30-726f4b708089.png)

**Comment by embray** [comment] 2018-03-29 15:27
The token is different every time you run the notebook server--it's (in theory) a security feature: http://jupyter-notebook.readthedocs.io/en/stable/security.html#security-in-the-jupyter-notebook-server

I'd be disinclined to disable it by default, since Sage for Windows can be installed on multi-user machines as well as single-user machines.  However, the above link shows how to disable it, which is probably fine if you're the only user of your machine.   A future version is also going to have a control panel for managing a notebook server in the background, and this could be an option configurable through the control panel.

**Comment by Quar** [comment] 2018-09-17 20:25
Alternatively after `docker run`, one can `grep` URL with token from `docker logs`:

For example, per image `sagemath/sagemath-jupyter`:

```bash
docker logs $(docker ps -q --filter ancestor=sagemath/sagemath-jupyter) 2>&1 | grep 'http://localhost'
```

and per image `sagemath/sagemath`:

```bash
docker logs $(docker ps -q --filter ancestor=sagemath/sagemath) 2>&1 | grep 'http://localhost'
```

For macOS, a very crude [Makefile](https://gist.github.com/Quar/ff756377b2ff179e87a156b1e6d43600) to lazily `run`, `stop`, `clean` and `restart`

**Comment by kirkro07** [comment] 2019-09-18 09:48
> Ran this command:
> 
> docker run -p 8888:8888 sagemath/sagemath-jupyter
> 
> Expected: Can go to the Jupyter notebook
> 
> Observed:
> 
> Got this error, no way to get the token. Docs should specify how to get token or default password.
> 
> ```
> Invalid password
> Token authentication is enabled. You need to open the notebook server with its first-time login token in the URL, or enable a password in order to gain access. The command:
> 
> jupyter notebook list
> will show you the URLs of running servers with their tokens, which you can copy and paste into your browser. For example:
> 
> Currently running servers:
> http://localhost:8888/?token=c8de56fa... :: /Users/you/notebooks
> Or you can paste just the token value into the password field on this page.
> 
> Cookies are required for authenticated access to notebooks.
> ```

where do i run that code

**Comment by embray** [comment] 2019-09-18 10:07
@kirkro07 What "code" are you referring to?  What's the issue you're having?

**Comment by embray** [comment] 2019-09-18 10:08
(Closing this issue since this image is obsolete, and I could not reproduce the original problem, but feel free to follow up.)

**Closed as completed by embray** 2019-09-18 10:08 UTC
